import styles from './faq.module.css'

function Q({ q, children }) {
  return (
    <div className={styles.card}>
      <h3 className={styles.question}>{q}</h3>
      <div className={styles.answer}>
        {children}
      </div>
    </div>
  )
}

export default function FAQ() {
  return (
    <div className={styles.container}>
      <h1>Frequently Asked Questions</h1>

      <Q q="What is Zodiac Protocol?">
        The Zodiac Protocol is an open-source protocol for deconstructing LPs into principal and yield tokens.
        The Zodiac Protocol and Interface were developed by Zodiac Labs.
        Check out the Introduction section of our docs for more info.
      </Q>

      <Q q="How do I use Zodiac Protocol?">
        The Zodiac Interface provides a way to interact with the smart contracts.
        To mint pLP or yLP tokens, head over the the Refract page.
        If your asset or maturity term does not exist, you will need to create a new vault.
        {/* For a more detailed walkthrough, check out our Help Guides.
        If you're a developer interested in building on top of Zodiac Protocol, please refer to our developer docs. */}
      </Q>

      <Q q="How does Zodiac Protocol work?">
        Zodiac refracts LP through vaults with maturity terms. Each vault locks refractable assets for the length of the term, minting a pLP and a yLP.
        Principal LP (pLP) tokens allow for investors to buy LP tokens at a discount while removing the uncertainty associated with trading fees.
        Yield LP (yLP) tokens allow for investors to claim a stream of trading fees generated by an LP, and removes impermanent loss risk inherent to constant function market makers.
        For a more in-depth description, check out the Concepts from the documentation.
      </Q>
    </div>
  )
}
