import Head from 'next/head'
import Image from 'next/image'
import styles from './index.module.css'
import Logo from '../components/logo.svg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>zodiac</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Logo className={styles.animated_logo} />
      </main>
    </div>
  )
}
